language: ruby
sudo: false

cache:
  bundler: true

rvm:
  - 2.4.1

env:
  matrix:
    - RAILS_VERSION=v5.2.0 GEM=ar:mysql2
    - RAILS_VERSION=v5.2.0 GEM=ar:sqlite3
    - RAILS_VERSION=v5.2.0 GEM=ar:postgresql
    - RAILS_VERSION=v5.2.1 GEM=ar:mysql2
    - RAILS_VERSION=v5.2.1 GEM=ar:sqlite3
    - RAILS_VERSION=v5.2.1 GEM=ar:postgresql

addons:
  postgresql: "9.4"

before_install:
  - unset BUNDLE_GEMFILE
  - gem update --system
  - gem update bundler

install:
  - bundle install --jobs=3 --retry=3
  - git clone https://github.com/rails/rails.git ~/build/rails
  - pushd ~/build/rails
  - git checkout $RAILS_VERSION
  - sed -i "s/Gem.ruby, '-w'/Gem.ruby, '-w0'/" ~/build/rails/activerecord/Rakefile
  - sed -i "s/t.warning = true/t.warning = false/g" ~/build/rails/activerecord/Rakefile
  - sed -i "/require 'support\/connection'/a \$LOAD_PATH.unshift\(File.expand_path\('~\/build\/malomalo\/activerecord-cached_at\/lib'\)\)\nrequire 'cached_at'" ~/build/rails/activerecord/test/cases/helper.rb
  - cat ~/build/rails/Gemfile
  - "sed -i \"/group :db do/a gem 'activerecord-cached_at', require: 'cached_at', path: File.expand_path\\('~\\/build\\/malomalo\\/activerecord-cached_at'\\)\" ~/build/rails/Gemfile"
  - sed -i "/rb-inotify/d" ~/build/rails/Gemfile
  - cat ~/build/rails/Gemfile
  - bundle install --jobs=3 --retry=3
  - popd

script:
  - bundle exec rake test
  - cd ~/build/rails && ci/travis.rb
